### ISSUE TITLE
add action integrity check in CI with ghasum

### ISSUE THREAD

**Issue by monperrus** [chains-project/maven-lockfile#937]
we use all integrity checking mechanisms, esp. when it's ours by @ghasum

https://github.com/ericcornelissen/ghasum/

**Comment by ericcornelissen** [comment]
Starting to use it _should_ be fairly easy (assuming the tool works), just download the binary and run `ghasum init` in the root of this project.

Beyond that it's a bit more complicated, the main points being:

- **Actually validating the integrity during the workflow.** In the project itself I do this by just `go run`ning the project ([example](https://github.com/ericcornelissen/ghasum/blob/82d6993e3d1e0787fa1c947b3c77e076cb33de52/.github/workflows/audit.yml#L29-L35)). That won't work for this (or other) projects. So you'd need to find a suitable way to run `ghasum` in the workflow. See also https://github.com/ericcornelissen/ghasum/issues/4
- **Supporting automatic updates.** You use Renovate to automatically update your actions but since Renovate doesn't know about `ghasum` it won't know to update the `gha.sum` file. Hence, for the time being, you'd have to update these manually or automatically using a workflow similar to https://github.com/ericcornelissen/ghasum/blob/82d6993e3d1e0787fa1c947b3c77e076cb33de52/.github/workflows/ghasum.yml. See also https://github.com/ericcornelissen/ghasum/issues/9

**Comment by ericcornelissen** [comment]
@monperrus / @LogFlames 

I have a started documenting a way to integrate `ghasum` into GitHub Actions workflows, please see [the draft documentation](https://github.com/chains-project/ghasum/tree/097ec89578a92e754a8da7c40a511dcdb10eb901?tab=readme-ov-file#integration) (and https://github.com/chains-project/ghasum/pull/229). I'd be happy to receive feedback on it as well as hearing if you'd be willing to adopt it 🙂

**Comment by monperrus** [comment]
nice!

**Comment by LogFlames** [comment]
It is now setup in #1211, verified to be working by adding an invalid hash in https://github.com/chains-project/maven-lockfile/actions/runs/15287455266/job/43000577578?pr=1211 , very nice and easy to follow instructions!

Two thoughts:
1. It currently outputs only "Ok" when successfully ran, which might be difficult to know that it was ghasum that output:ed it. Some green check would be nice, e.g. "✅ Successfully verified integrity of Github Actions" (or similar message). Listing which actions were verified could also be beneficial to see that it works correctly. Maybe a `-verbose` flag to make it optional.
2. As it is quite a lot of yaml I created a separate [`.github/actions/ghasum/action.yml`](https://github.com/chains-project/maven-lockfile/blob/937-add-action-integrity-check-in-ci-with-ghasum/.github/actions/ghasum/action.yml) which downloads and runs ghasum. This also makes it easier to update the ghasum version without having to change it (and the checksum) in all 12 actions.
   1. I had to add `shell: bash`, unsure why it was needed when ran as a composite action and not needed when ran in a normal step in the action, but maybe this could be added to the example template?
   2. I wish to verify with you that this still fulfills the integrity. `actions/checkout@4.2.2` must still be ran before the local action can be run (same as when running "inline"), and since the ghasum/action.yml is then locally defined in the maven-lockfile I think there should not be any additional way this could be tampered with that would not be possible if defining the ghasum check "inline". Does this hold? Or does doing it this way increase the attack surface?

**Comment by ericcornelissen** [comment]
> 1. It currently outputs only "Ok" when successfully ran, which might be difficult to know that it was ghasum that output:ed it. Some green check would be nice, e.g. "✅ Successfully verified integrity of Github Actions" (or similar message). Listing which actions were verified could also be beneficial to see that it works correctly. Maybe a `-verbose` flag to make it optional.

Point taken that the output could be richer. However, one contributing factor here is that the GitHub Actions logs don't show you the commands that it ran...

One way you could address that here (before I update `ghasum`) is to split your action into two steps: one that runs the "Download the ghasum CLI" part and one that runs the "Verify the action checksums" part.


> 2. As it is quite a lot of yaml I created a separate [`.github/actions/ghasum/action.yml`](https://github.com/chains-project/maven-lockfile/blob/937-add-action-integrity-check-in-ci-with-ghasum/.github/actions/ghasum/action.yml) which downloads and runs ghasum. This also makes it easier to update the ghasum version without having to change it (and the checksum) in all 12 actions.

That's a great idea, I'll try to work something like that into the documentation over at https://github.com/chains-project/ghasum/pull/229 - thanks!

One thing to consider is that different runners (specifically OSes) require different logic, so if you start using different runners I guess you have to create separate actions? Maybe there is some way to run a different script based on the current runner name or OS, that would be cleaner.

An alternative I've been thinking about is to include a script in the [`ghasum` release assets](https://github.com/chains-project/ghasum/releases) which bundles all the steps currently embedded in the YAML. However, that would still require checking the checksum of the script itself so although it would be shorter, it won't be as short as having a local action.


> 2.1. I had to add `shell: bash`, unsure why it was needed when ran as a composite action and not needed when ran in a normal step in the action, but maybe this could be added to the example template?

I'm not sure, I guess it's just required for composite actions 🤔 Could you point me to the error you observed without setting `shell: bash`?

If it's a composite actions thing I'm inclined not to add it to the workflow examples, but when I add an example of using a local action I'll definitely specify the `shell: bash` explicitly.


> 2.2. I wish to verify with you that this still fulfills the integrity. `actions/checkout@4.2.2` must still be ran before the local action can be run (same as when running "inline"), and since the ghasum/action.yml is then locally defined in the maven-lockfile I think there should not be any additional way this could be tampered with that would not be possible if defining the ghasum check "inline". Does this hold? Or does doing it this way increase the attack surface?

Yes, I agree, this should be just as safe as running `ghasum` inline.

**Comment by LogFlames** [comment]
> One way you could address that here (before I update `ghasum`) is to split your action into two steps: one that runs the "Download the ghasum CLI" part and one that runs the "Verify the action checksums" part.

That is a good idea 👍 

> One thing to consider is that different runners (specifically OSes) require different logic, so if you start using different runners I guess you have to create separate actions? Maybe there is some way to run a different script based on the current runner name or OS, that would be cleaner.

There is `${{ runner.os }}` and `${{ runner.arch }}` available which outputs "Linux", "macOS", or "Windows" and "X64", "ARM64" respectively. I don't know how there interact with docker or self-hosted runners though. Test runs of file [logflames/maven-lockfile-action-test-project/.github/workflows/test.yml](https://github.com/LogFlames/maven-lockfile-action-test-project/blob/main/.github/workflows/test.yml) available here:
- Linux: https://github.com/LogFlames/maven-lockfile-action-test-project/actions/runs/15299091588/job/43035010001
- Mac: https://github.com/LogFlames/maven-lockfile-action-test-project/actions/runs/15299091588/job/43035010522
- Windows: https://github.com/LogFlames/maven-lockfile-action-test-project/actions/runs/15299091588/job/43035011013

These could maybe be able to determine which executable to download and which checksum to check it against - although all checksums would still need to be provided. Maybe the entire checksum-sha512 could be pasted into the environment for convenience.

> I'm not sure, I guess it's just required for composite actions 🤔 Could you point me to the error you observed without setting shell: bash?

Here is an example-run which gave the "missing shell" error: https://github.com/chains-project/maven-lockfile/actions/runs/15287332584/job/43000226627?pr=1211

```log
Error: /home/runner/work/maven-lockfile/maven-lockfile/./.github/actions/ghasum/action.yml (Line: 14, Col: 7): Required property is missing: shell
Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/maven-lockfile/maven-lockfile/./.github/actions/ghasum/action.yml (Line: 14, Col: 7): Required property is missing: shell
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Failed to load /home/runner/work/maven-lockfile/maven-lockfile/./.github/actions/ghasum/action.yml
```

> If it's a composite actions thing I'm inclined not to add it to the workflow examples, but when I add an example of using a local action I'll definitely specify the shell: bash explicitly.

That sounds like a very good option, no need to bloat the normal inline yml. When running it inline it worked without `shell: bash`, so I agree its probably a compose/local action thing.

> Yes, I agree, this should be just as safe as running ghasum inline.
👍

**Comment by ericcornelissen** [comment]
> There is `${{ runner.os }}` and `${{ runner.arch }}` available which outputs "Linux", "macOS", or "Windows" and "X64", "ARM64" respectively. I don't know how there interact with docker or self-hosted runners though.

Thanks for the suggestion, I've used this in the latest iteration of https://github.com/chains-project/ghasum/pull/229 👍 

> These could maybe be able to determine which executable to download and which checksum to check it against - although all checksums would still need to be provided. Maybe the entire checksum-sha512 could be pasted into the environment for convenience.

That's a good suggestion. For now I'll leave it as an improvement to do in the future.


> Here is an example-run which gave the "missing shell" error: https://github.com/chains-project/maven-lockfile/actions/runs/15287332584/job/43000226627?pr=1211
> 
> ```
> Error: /home/runner/work/maven-lockfile/maven-lockfile/./.github/actions/ghasum/action.yml (Line: 14, Col: 7): Required property is missing: shell
> Error: GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/maven-lockfile/maven-lockfile/./.github/actions/ghasum/action.yml (Line: 14, Col: 7): Required property is missing: shell
>    at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
>    at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
>    at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
> Error: Failed to load /home/runner/work/maven-lockfile/maven-lockfile/./.github/actions/ghasum/action.yml
> ```

That looks like a composite action-specific error, so I'll keep the inline examples as is but I've included it in the local action example.
